'use client';
import {useState,type ReactNode,type CSSProperties} from 'react';
import {Search,ArrowUpRight,ArrowRight,Layers,RotateCcw,Info} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {systems,taxonFocus} from './systems-data';
import {dinosaurs,type Dino} from './data';

export default function BodySystems({dino,onSelect,viewer}:{dino:Dino;onSelect:(id:string)=>void;viewer:ReactNode}){
 const [systemId,setSystemId]=useState('skeleton');const [part,setPart]=useState(0);const [query,setQuery]=useState('');const [mode,setMode]=useState('map');
 const system=systems.find(s=>s.id===systemId)!;const structure=system.structures[part];
 const matches=systems.flatMap(s=>s.structures.map((p,i)=>({s,p,i}))).filter(({s,p})=>`${s.name} ${p.name}`.toLowerCase().includes(query.toLowerCase()));
 const respiratoryNote=['triceratops','stegosaurus','parasaurolophus'].includes(dino.id)?'For this ornithischian, do not assume the same invasive air-sac arrangement documented in many theropods and sauropods. The soft respiratory anatomy is less securely constrained.':'This dinosaur belongs to a saurischian lineage. Pneumatic bones in theropods and sauropods support respiratory air-sac reconstructions, but exact soft anatomy still needs taxon-specific evidence.';
 const pick=(id:string,i=0)=>{setSystemId(id);setPart(i)};
 return <section className="body-atlas" style={{'--system-colour':system.colour} as CSSProperties}>
  <div className="atlas-heading"><div><span className="micro-label">COMPARATIVE DINOSAUR ANATOMY</span><h1>Body systems</h1></div><div className="atlas-species"><label htmlFor="atlas-species">Study a dinosaur</label><Select value={dino.id} onValueChange={onSelect}><SelectTrigger id="atlas-species"><SelectValue/></SelectTrigger><SelectContent>{dinosaurs.map(d=><SelectItem key={d.id} value={d.id}>{d.name}</SelectItem>)}</SelectContent></Select></div></div>
  <div className="atlas-layout">
   <aside className="atlas-systems"><div className="atlas-panel-heading"><Layers size={17}/><h2>Systems</h2><span>08</span></div><label className="search-field"><Search size={16}/><span className="sr-only">Find a system or structure</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find a structure…"/></label>
   {query?<div className="atlas-search" aria-label="Matching structures">{matches.map(({s,p,i})=><button key={s.id+i} onClick={()=>{pick(s.id,i);setQuery('');setMode('map')}}><strong>{p.name}</strong><small>{s.name}</small></button>)}{!matches.length&&<p>No structures match. <button onClick={()=>setQuery('')}>Clear search</button></p>}</div>:<nav aria-label="Body systems">{systems.map((s,i)=><button key={s.id} className={s.id===systemId?'selected':''} aria-pressed={s.id===systemId} onClick={()=>pick(s.id)}><span className="system-swatch" style={{background:s.colour}}/><span>{s.name}</span><small>{String(i+1).padStart(2,'0')}</small></button>)}</nav>}
   <p className="atlas-key"><strong>Read the evidence</strong><br/>Fossil evidence · Comparative inference · Mixed evidence</p><button className="quiet-button" onClick={()=>{pick('skeleton');setQuery('');setMode('map')}}><RotateCcw size={15}/> Reset systems</button></aside>
   <div className="atlas-centre"><div className="atlas-system-title"><span className="micro-label">{dino.name.toUpperCase()} · SYSTEM {String(systems.indexOf(system)+1).padStart(2,'0')}</span><h2>{system.name}</h2><p>{system.summary}</p></div>
    <Tabs value={mode} onValueChange={setMode}><TabsList className="atlas-view-tabs" aria-label="Anatomy view"><TabsTrigger value="map">Function map</TabsTrigger><TabsTrigger value="specimen">360° specimen</TabsTrigger></TabsList><TabsContent value="map"><div className="system-map"><div className="map-caption"><span>FUNCTIONAL SCHEMATIC</span><span>{system.relationship}</span></div><div className={`system-path ${system.id==='circulatory'?'circuit':''}`} aria-label={`${system.name} functional structures`}>{system.structures.map((p,i)=><div className="map-step" key={p.name}><button aria-pressed={part===i} className={`structure-node ${part===i?'selected':''}`} onClick={()=>setPart(i)}><span className="node-number">0{i+1}</span><strong>{p.name}</strong><small>{p.confidence}</small></button>{i<2&&<ArrowRight className="path-arrow" size={23} aria-hidden="true"/>}</div>)}</div><p className="map-explainer">{system.id==='circulatory'?'Heart → lungs → heart → body → heart. The two circuits share the pump.':system.id==='respiratory'?'Connections represent functional relationships, not a one-pass sequence of airflow.':system.id==='skeleton'||system.id==='surface'?'Linked components are shown together; arrows do not represent a biological flow.':'Follow the linked stages, then select a structure to inspect its evidence.'}</p><div className="map-boundary"><Info size={17}/><p>This map explains relationships. It is not an anatomical reconstruction and does not show organ positions, shapes or scale.</p></div></div></TabsContent><TabsContent value="specimen">{viewer}<p className="atlas-model-note">The specimen gives 3D context. System selection changes the learning notes; these models do not contain separable organ layers. <a href="/credits">Model credits ↗</a></p></TabsContent></Tabs>
    <div className="atlas-taxon"><span className="micro-label">LOOK FOR IN {dino.name.toUpperCase()}</span><p>{taxonFocus[dino.id]}</p>{system.id==='respiratory'&&<p>{respiratoryNote}</p>}{system.id==='digestive'&&<p>Profile diet: {dino.diet}. Use the teeth and jaw to evaluate this interpretation; the diagram does not assign an exact gut shape to {dino.name}.</p>}{system.id==='skeleton'&&<p>{dino.anatomy[0].look}</p>}<div className="source-links">{dino.sources.slice(0,1).map(s=><a key={s.url} href={s.url} target="_blank" rel="noreferrer">Species reference <ArrowUpRight size={14}/></a>)}</div></div>
   </div>
   <aside className="atlas-details" aria-live="polite"><span className="micro-label">STRUCTURE {part+1} / {system.structures.length}</span><h2>{structure.name}</h2><span className="atlas-evidence">{structure.confidence}</span><h3>What it does</h3><p>{structure.role}</p><h3>How we know</h3><p>{structure.evidence}</p><div className="atlas-limit"><h3>What remains uncertain</h3><p>{system.limit}</p></div><div className="structure-pagination" aria-label="Inspect structures">{system.structures.map((p,i)=><button key={p.name} aria-label={`Inspect ${p.name}`} aria-pressed={part===i} onClick={()=>setPart(i)}>{i+1}</button>)}</div><h3>Sources & further study</h3><div className="source-links">{system.sources.map(s=><a key={s.url} href={s.url} target="_blank" rel="noreferrer">{s.label}<ArrowUpRight size={14}/></a>)}</div></aside>
  </div>
  <p className="atlas-credit">Interaction concept inspired by <a href="https://human-atlas-seven.vercel.app/" target="_blank" rel="noreferrer">Human Atlas</a>. Dinosaur content and functional schematics created for Mesozoic Lab by Foo Huey Chyun. No Human Atlas code or anatomical assets are used.</p>
 </section>
}
