export type Reconstruction={id:string;taxon:string;image:string;source:string;artist:string;licence:string;licenceUrl:string;note:string};
const commons='https://commons.wikimedia.org/wiki/File:';
const shareAlike={licence:'CC BY-SA 4.0',licenceUrl:'https://creativecommons.org/licenses/by-sa/4.0/'};
export const reconstructions:Reconstruction[]=[
{id:'triceratops',taxon:'Triceratops horridus',image:'/reconstructions/triceratops.png',source:commons+'Triceratops_horridus.png',artist:'Connor Ashbridge',...shareAlike,note:'Compare the fleshed-out body and horn-bearing skull with the composite skeleton. Colour and the detailed soft-tissue outline are interpretations.'},
{id:'tyrannosaurus',taxon:'Tyrannosaurus rex',image:'/reconstructions/tyrannosaurus.jpg',source:commons+'Tyrannosaurus_rex_Reconstruction_by_Nobu_Tamura.jpg',artist:'Nobu Tamura; source crop by Monsieur X',...shareAlike,note:'This 2018 artwork presents one interpretation of body shape and skin covering. Colour, facial soft tissues and the extent of any feather covering are not established by this illustration.'},
{id:'stegosaurus',taxon:'Stegosaurus ungulatus',image:'/reconstructions/stegosaurus.png',source:commons+'Stegosaurus_ungulatus_colored_final.png',artist:'Slate Weasel',licence:'Public domain',licenceUrl:commons+'Stegosaurus_ungulatus_colored_final.png#Licensing',note:'Compare the plates, tail spikes and limb proportions. The illustration follows published skeletal reconstructions; its colour pattern is artistic.'},
{id:'diplodocus',taxon:'Diplodocus carnegii',image:'/reconstructions/diplodocus.jpg',source:commons+'Diplodocus_carnegii.jpg',artist:'Fred Wierum',...shareAlike,note:'Look at how muscles and other soft tissues change the outline of the neck, trunk and tail. A drawn neck pose does not establish its full range of movement.'},
{id:'velociraptor',taxon:'Velociraptor mongoliensis',image:'/reconstructions/velociraptor.png',source:commons+'Velociraptor_Restoration.png',artist:'Fred Wierum',...shareAlike,note:'The feathered arms reflect evidence from fossil quill knobs and feathered relatives. The exact plumage pattern and colour remain artistic choices.'},
{id:'spinosaurus',taxon:'Spinosaurus aegyptiacus',image:'/reconstructions/spinosaurus.png',source:commons+'Spinosaurus_aegyptiacus_life_reconstruction.png',artist:'Connor Ashbridge',licence:'CC BY 4.0',licenceUrl:'https://creativecommons.org/licenses/by/4.0/',note:'This 2026 illustration offers a different reconstruction from the artistic 3D model. Body proportions, posture and aquatic behaviour remain subjects of research; this image is not proof of a particular swimming ability.'},
{id:'parasaurolophus',taxon:'Parasaurolophus walkeri',image:'/reconstructions/parasaurolophus.png',source:commons+'Life_reconstruction_of_Parasaurolophus_walkeri.png',artist:'Connor Ashbridge',...shareAlike,note:'This developed crest contrasts with the juvenile Parasaurolophus specimen in the 3D viewer. The two views represent different growth stages and are not the same individual.'},
{id:'allosaurus',taxon:'Allosaurus fragilis',image:'/reconstructions/allosaurus.jpg',source:commons+'Allosaurus_Revised.jpg',artist:'Fred Wierum',...shareAlike,note:'The 3D specimen shows a skull. This full-body reconstruction provides wider context, with proportions based on a skeletal reconstruction of UUVP 6000.'}
];
