export type Structure = {name:string; role:string; evidence:string; confidence:'Fossil evidence'|'Comparative inference'|'Mixed evidence'};
export type BodySystem = {id:string; name:string; colour:string; summary:string; relationship:string; limit:string; structures:Structure[]; sources:{label:string;url:string}[]};
const nhm={label:'Barrett & Hendry · How we study dinosaurs (NHM)',url:'https://www.nhm.ac.uk/discover/what-can-scientists-learn-about-dinosaurs-and-how.html'};
const locomotion={label:'Falkingham et al. (2025) · Reconstructing dinosaur locomotion',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC11732409/'};
export const systems:BodySystem[]=[
{id:'skeleton',name:'Skeleton & joints',colour:'#d5d9aa',summary:'The supporting framework that protects organs and provides levers for movement.',relationship:'Support and articulation',limit:'Mounted specimens can combine individuals, casts and restored bones. Joint cartilage and habitual poses must be reconstructed.',structures:[
{name:'Skull & jaws',role:'Protect the brain and support the feeding apparatus.',evidence:'Bone shape and tooth wear can be examined directly. Muscle force and feeding behaviour require further interpretation.',confidence:'Fossil evidence'},
{name:'Vertebral column',role:'Supports the trunk and links the head, body and tail.',evidence:'Articulated vertebrae and joint surfaces constrain possible movement, but do not reveal a single habitual posture.',confidence:'Fossil evidence'},
{name:'Girdles & limbs',role:'Transfer loads between the body and the ground.',evidence:'Limb bones, joint geometry and trackways provide complementary evidence about stance and movement.',confidence:'Fossil evidence'}],sources:[nhm,locomotion]},
{id:'muscles',name:'Muscles & movement',colour:'#f19883',summary:'Muscles pull on bones across joints. Their arrangement helps explain feeding, walking and tail movement.',relationship:'Force through a joint',limit:'The displayed 3D models do not contain separable muscles. Muscle volume, strength and activation are reconstructed, not measured from living dinosaurs.',structures:[
{name:'Muscle attachment',role:'An origin anchors one end of a muscle to the skeleton.',evidence:'Scars and ridges can indicate attachment regions. Living birds and crocodilians help identify plausible muscles.',confidence:'Mixed evidence'},
{name:'Muscle & tendon',role:'Contraction produces tension that tendons transmit to bone.',evidence:'Soft-tissue paths are constrained by skeletal geometry and comparative anatomy. Several reconstructions may fit the same bones.',confidence:'Comparative inference'},
{name:'Moving bone',role:'A muscle pulls at its insertion and creates a turning effect around a joint.',evidence:'Models estimate moment arms and movement. Results depend on assumptions about cartilage, posture and muscle size.',confidence:'Mixed evidence'}],sources:[locomotion]},
{id:'respiratory',name:'Breathing',colour:'#82cbdc',summary:'Lungs exchange gases. Evidence for additional air sacs is especially strong in many theropods and sauropods.',relationship:'Gas exchange and ventilation',limit:'Air sacs are ventilatory reservoirs, not the main gas-exchange surface. Their exact arrangement is not known for every dinosaur group.',structures:[
{name:'Airway',role:'Connects the outside air with the respiratory organs.',evidence:'Bony nasal passages constrain part of the airway. The trachea and its soft tissues are usually inferred.',confidence:'Mixed evidence'},
{name:'Lungs',role:'Transfer oxygen into blood and carbon dioxide out of it.',evidence:'Living archosaurs inform reconstructions. Bone cavities alone cannot reveal every detail of a dinosaur lung.',confidence:'Comparative inference'},
{name:'Air sacs & diverticula',role:'Air sacs assist ventilation; extensions can enter bones in some groups.',evidence:'Diagnostic openings and internal chambers reveal skeletal pneumaticity. Lack of these features does not by itself prove an absence of all air sacs.',confidence:'Mixed evidence'}],sources:[{label:'Wedel · Postcranial pneumaticity and the avian lung',url:'https://arxiv.org/abs/1302.3267'},{label:'Butler et al. (2012) · Evidence for skeletal pneumaticity',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC3314707/'}]},
{id:'digestive',name:'Feeding & digestion',colour:'#e4bd70',summary:'Food is acquired, broken down and absorbed. Fossils reveal more about diet than the precise shape of the gut.',relationship:'Food and nutrient pathway',limit:'These are functional stages, not a species-specific organ map. A large abdomen alone does not establish exact gut anatomy.',structures:[
{name:'Mouth & teeth',role:'Acquire food and, in some dinosaurs, process it before swallowing.',evidence:'Teeth, wear surfaces and jaw anatomy reveal feeding adaptations.',confidence:'Fossil evidence'},
{name:'Stomach & intestine',role:'Break down food and absorb nutrients.',evidence:'These organs are mainly inferred. Exceptional preserved meals give snapshots of diet rather than a complete digestive system.',confidence:'Mixed evidence'},
{name:'Waste',role:'Material that is not absorbed leaves the digestive tract.',evidence:'Coprolites are fossilised droppings. Their contents can indicate diet, though identifying the producer is often difficult.',confidence:'Fossil evidence'}],sources:[nhm]},
{id:'circulatory',name:'Heart & circulation',colour:'#e68caf',summary:'Blood transports gases and nutrients. The broad plan is inferred from living relatives, while detailed dinosaur vessels remain uncertain.',relationship:'Two connected circuits',limit:'This functional circuit does not depict preserved dinosaur arteries or veins. A four-chambered heart alone does not establish metabolic rate.',structures:[
{name:'Heart',role:'Pumps blood around the pulmonary and systemic circuits.',evidence:'Birds and crocodilians both have four-chambered hearts. This supports an inference for their extinct dinosaur relatives, not a direct observation of a fossil heart.',confidence:'Comparative inference'},
{name:'Pulmonary circuit',role:'Moves blood between the heart and lungs for gas exchange.',evidence:'The broad function follows living vertebrate anatomy. Exact pressure and flow in an extinct species are not directly known.',confidence:'Comparative inference'},
{name:'Systemic circuit',role:'Delivers oxygen and nutrients to tissues and returns blood to the heart.',evidence:'Detailed branching is not recoverable from these skeletons. Body dimensions alone do not resolve physiology.',confidence:'Comparative inference'}],sources:[{label:'Koshiba-Takeuchi et al. (2009) · Reptilian heart development',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC2753965/'},{label:'Wang et al. (2018) · The beat goes on',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC5940358/'}]},
{id:'nervous',name:'Brain & senses',colour:'#b5a1ed',summary:'Sensory input, neural processing and motor signals coordinate an animal’s responses.',relationship:'Sensation to response',limit:'An endocast records the inside of the braincase, not necessarily the exact brain. Brain size alone cannot establish intelligence.',structures:[
{name:'Sensory structures',role:'Detect information such as light, sound and body position.',evidence:'Orbits and inner-ear spaces constrain aspects of sensory anatomy. Soft tissues and behaviour need additional inference.',confidence:'Mixed evidence'},
{name:'Brain & spinal cord',role:'Integrate signals and coordinate responses.',evidence:'CT-based endocasts reveal the braincase cavity. Brain and cavity differ by region, age and animal group.',confidence:'Mixed evidence'},
{name:'Peripheral nerves',role:'Carry signals between the central nervous system and the body.',evidence:'Some skull openings mark nerve exits. Most complete nerve paths are reconstructed by comparison with living animals.',confidence:'Comparative inference'}],sources:[{label:'Watanabe et al. (2018) · Are endocasts good proxies for brains?',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC6365484/'},{label:'Balanoff et al. (2024) · Dinosaur palaeoneurology',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC11651910/'}]},
{id:'surface',name:'Skin & feathers',colour:'#8dc8a3',summary:'The body surface protects the animal. Scales and feathers can also support insulation and signalling.',relationship:'Covering and possible functions',limit:'The colour of a displayed artistic model is not evidence. Preserved skin or feathers from one region do not establish the covering of the whole animal.',structures:[
{name:'Skin & scales',role:'Form a protective boundary with the environment.',evidence:'Skin impressions record local surface texture. Preservation is uneven across body regions and taxa.',confidence:'Fossil evidence'},
{name:'Feathers',role:'Can contribute to insulation, display and, in flying dinosaurs, flight.',evidence:'Feathers are directly preserved in some dinosaurs. Velociraptor forearm quill knobs provide skeletal evidence of attached feathers.',confidence:'Mixed evidence'},
{name:'Colour & display',role:'Surface patterns may help communication or concealment.',evidence:'Detailed appearance is unknown for the models here. A plausible-looking reconstruction is not proof of a particular colour or behaviour.',confidence:'Comparative inference'}],sources:[nhm,{label:'Turner et al. (2007) · Feather quill knobs in Velociraptor',url:'https://pubmed.ncbi.nlm.nih.gov/17885130/'}]},
{id:'reproductive',name:'Reproduction & growth',colour:'#d8a6d3',summary:'Eggs, embryos and bone tissues help reconstruct dinosaur life cycles.',relationship:'Life cycle, not an organ layout',limit:'Egg-laying is well supported, but detailed reproductive organs and sex are not established for the displayed models.',structures:[
{name:'Egg formation',role:'Produces and packages the developing offspring.',evidence:'Reproductive organs are generally inferred. Medullary bone identified in a T. rex specimen supports a link with egg production.',confidence:'Mixed evidence'},
{name:'Egg & embryo',role:'Supports development before hatching.',evidence:'Fossilised eggs with embryos can identify the dinosaur producer more securely than isolated eggshell alone.',confidence:'Fossil evidence'},
{name:'Growth',role:'Transforms a hatchling into a larger, mature animal.',evidence:'Bone microstructure can preserve growth information. A juvenile skeleton is not simply a scaled-down adult.',confidence:'Fossil evidence'}],sources:[nhm,{label:'Schweitzer et al. (2016) · Chemistry of reproductive tissue in T. rex',url:'https://www.nature.com/articles/srep23099'}]}
];
export const taxonFocus:Record<string,string>={
triceratops:'Start with the beak, tooth batteries and horn-bearing skull. The scan is a composite skeleton, so it does not establish the soft anatomy of one individual.',
tyrannosaurus:'Compare the large skull with the hindlimbs. Reproductive tissue has been studied in another T. rex specimen, not in the model displayed here.',
stegosaurus:'Inspect the plates, tail spikes and limb proportions. Plate shape is visible; proposed functions such as signalling need separate evidence.',
diplodocus:'Follow the long neck and tail. Pneumatic vertebrae in sauropods are especially informative about respiratory extensions into the skeleton.',
velociraptor:'Study the forelimbs and enlarged foot claw. Quill knobs in fossil Velociraptor provide evidence for arm feathers, but the model’s colours are artistic.',
spinosaurus:'Compare the long jaws, sail and tail with other theropods. Swimming ability and aquatic habits remain debated; this artistic model does not settle those questions.',
parasaurolophus:'Trace the skull crest and feeding apparatus. The model represents a juvenile, so proportions and crest development differ from an adult.',
allosaurus:'This model is a skull. It supports close study of jaws and openings, while the body-system diagrams provide general context beyond the preserved model.'
};
