export const anatomySources={
 skeleton:{label:'Natural History Museum · Tyrannosaurus',url:'https://www.nhm.ac.uk/discover/dino-directory/tyrannosaurus.html'},
 muscles:{label:'Hutchinson et al. (2011) · T. rex body and limb reconstruction',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC3192160/'},
 breathing:{label:'Brocklehurst et al. (2020) · Respiratory evolution in archosaurs',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC7017431/'},
 senses:{label:'Witmer & Ridgely (2009) · Tyrannosaur braincase and senses',url:'https://doi.org/10.1002/ar.20983'},
 skin:{label:'Bell et al. (2017) · Tyrannosauroid skin fossils',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC5493735/'}
};
export const anatomySystems=[
 {id:'skeleton',name:'Skeleton',colour:'#8b743f'},
 {id:'muscles',name:'Muscles',colour:'#b04448'},
 {id:'respiration',name:'Respiration',colour:'#217d9a'},
 {id:'digestion',name:'Digestion',colour:'#a56220'},
 {id:'senses',name:'Brain & senses',colour:'#7950a2'},
 {id:'surface',name:'Skin & covering',colour:'#347348'}
] as const;
export type SystemId=typeof anatomySystems[number]['id'];
export type AnatomyPart={id:string;system:SystemId;name:string;function:string;evidence:string;limit:string;kind:'Fossil evidence'|'Comparative inference'|'Mixed evidence';source:keyof typeof anatomySources};
export const anatomyParts:AnatomyPart[]=[
{id:'skull',system:'skeleton',name:'Skull & lower jaw',function:'Support the teeth and provide attachment areas for the jaw muscles.',evidence:'Skulls preserve the bony framework and openings. The display simplifies many separate bones into a teaching shape.',limit:'This is not a scan or a specimen-specific skull reconstruction.',kind:'Fossil evidence',source:'skeleton'},
{id:'spine',system:'skeleton',name:'Vertebral column & tail',function:'Support the trunk and transmit forces between the body and limbs. The tail also helps balance the body.',evidence:'Fossilised vertebrae record the spinal column. Joint tissues are not shown here.',limit:'Vertebra counts and joint motion are not represented precisely.',kind:'Fossil evidence',source:'skeleton'},
{id:'ribs',system:'skeleton',name:'Rib cage',function:'Supports the chest wall around the internal organs.',evidence:'Ribs survive as fossils; their three-dimensional arrangement is reconstructed.',limit:'These arcs indicate the rib region rather than exact rib geometry or a complete breathing mechanism.',kind:'Fossil evidence',source:'breathing'},
{id:'pelvis',system:'skeleton',name:'Pelvis',function:'Transfers weight to the hindlimbs and anchors large muscles.',evidence:'The ilium, pubis and ischium are preserved in fossil skeletons.',limit:'The schematic does not resolve the separate pelvic bones.',kind:'Fossil evidence',source:'skeleton'},
{id:'hindlimbs',system:'skeleton',name:'Hindlimbs & feet',function:'Bear body weight and provide propulsion during walking.',evidence:'Limb bones constrain proportions. Movement studies combine them with estimates of muscles and body mass.',limit:'A posed skeleton cannot establish top speed or gait by itself.',kind:'Mixed evidence',source:'muscles'},
{id:'forelimbs',system:'skeleton',name:'Forelimbs',function:'Articulated at the shoulders and elbows; the hands had two principal fingers.',evidence:'Fossils preserve the short arms and two-fingered hands.',limit:'Their precise behavioural role remains uncertain.',kind:'Fossil evidence',source:'skeleton'},
{id:'jaw-muscles',system:'muscles',name:'Jaw adductors',function:'Close the lower jaw to grip and process food.',evidence:'Bony attachment regions and living relatives guide reconstruction of the muscle paths.',limit:'The highlighted volume is illustrative. It does not measure bite force.',kind:'Mixed evidence',source:'muscles'},
{id:'hip-muscles',system:'muscles',name:'Hip & thigh muscles',function:'Move and stabilise the hindlimbs while supporting the body.',evidence:'Attachment areas and biomechanical models constrain plausible muscle arrangements.',limit:'Muscle bulk is estimated rather than preserved as shown.',kind:'Mixed evidence',source:'muscles'},
{id:'tail-muscle',system:'muscles',name:'Caudofemoral region',function:'Tail-based muscles helped pull the thigh backwards.',evidence:'Tail and femoral anatomy help reconstruct these muscles by comparison with living reptiles.',limit:'Exact muscle boundaries and activation patterns remain inferred.',kind:'Mixed evidence',source:'muscles'},
{id:'trachea',system:'respiration',name:'Trachea',function:'Conducts air from the throat towards the lungs.',evidence:'A windpipe is inferred from the respiratory anatomy of living archosaurs.',limit:'Its route and diameter here are schematic, not preserved in this model.',kind:'Comparative inference',source:'breathing'},
{id:'lungs',system:'respiration',name:'Lungs',function:'Exchange oxygen and carbon dioxide with the blood.',evidence:'Archosaur comparisons and skeletal pneumaticity inform respiratory reconstructions.',limit:'The paired shapes locate a general dorsal lung region. They do not reproduce lung microstructure.',kind:'Comparative inference',source:'breathing'},
{id:'air-sacs',system:'respiration',name:'Air sac regions',function:'Air sacs in an avian-style system assist ventilation; gas exchange occurs in the lungs.',evidence:'Air-filled spaces in theropod bones support extensions of the respiratory system.',limit:'The number, boundaries and sizes of these sacs are illustrative. No exact T. rex ventilation cycle is simulated.',kind:'Mixed evidence',source:'breathing'},
{id:'teeth',system:'digestion',name:'Teeth',function:'Grip flesh and withstand substantial feeding loads.',evidence:'Fossilised teeth record their robust form and serrated cutting edges.',limit:'The diagram simplifies tooth shapes and number. Teeth do not establish every feeding behaviour.',kind:'Fossil evidence',source:'skeleton'},
{id:'oesophagus',system:'digestion',name:'Oesophagus',function:'Carries swallowed food towards the stomach.',evidence:'An oesophagus is inferred from living vertebrate anatomy.',limit:'The displayed path is a teaching guide. No preserved T. rex oesophagus is represented.',kind:'Comparative inference',source:'skeleton'},
{id:'stomach',system:'digestion',name:'Stomach & intestinal region',function:'Break down food and absorb nutrients.',evidence:'A digestive tract is inferred from living relatives and the animal’s feeding adaptations.',limit:'Organ shape, length and packing are unknown here. The coil is a location marker, not a recovered gut.',kind:'Comparative inference',source:'skeleton'},
{id:'brain',system:'senses',name:'Brain region',function:'Coordinates sensory processing and movement.',evidence:'CT studies reconstruct the cavity within the braincase, called an endocast.',limit:'An endocast is not the brain itself. This enlarged marker cannot establish neuron counts or intelligence.',kind:'Mixed evidence',source:'senses'},
{id:'eyes',system:'senses',name:'Eyes & visual region',function:'Receive visual information from the surroundings.',evidence:'The skull constrains eye placement. Soft tissues are reconstructed.',limit:'The eye markers are enlarged for selection. Colour and exact visual performance are not shown.',kind:'Mixed evidence',source:'senses'},
{id:'covering',system:'surface',name:'Body covering',function:'Protects the animal and forms an interface with its environment.',evidence:'Skin impressions document scales in several sampled T. rex body regions.',limit:'Patchy preservation does not provide a complete covering map. This smooth envelope does not establish colour or rule out all feathers.',kind:'Mixed evidence',source:'skin'}
];
