'use client';
import {useState} from 'react';
import LicensedSkeleton from './licensed-skeleton';
import dynamic from 'next/dynamic';
import {Layers,RotateCcw,ArrowUpRight} from 'lucide-react';
import {Slider} from '@/components/ui/slider';
import {Switch} from '@/components/ui/switch';
import {anatomyParts,anatomySystems,anatomySources,type SystemId} from './trex-anatomy-data';
const AnatomyScene=dynamic(()=>import('./trex-anatomy-scene'),{ssr:false,loading:()=> <div className="anatomy-canvas anatomy-loading" role="status">Opening the anatomy model…</div>});
export default function TrexAnatomy({onSpecimen}:{onSpecimen:()=>void}){
 const [system,setSystem]=useState<SystemId>('skeleton');const [selected,setSelected]=useState('skull');const [opacity,setOpacity]=useState(9);const [isolated,setIsolated]=useState(false);const [reset,setReset]=useState(0);const [angle,setAngle]=useState<'side'|'front'|'top'>('side');
 const part=anatomyParts.find(p=>p.id===selected)!;const activeSystem=anatomySystems.find(s=>s.id===system)!;const source=anatomySources[part.source];
 function changeSystem(id:SystemId){setSystem(id);setSelected(anatomyParts.find(p=>p.system===id)!.id)}
 return <section className="anatomy-atlas">
 <header className="anatomy-heading"><div><span className="micro-label">EXPLORE ANATOMY · FIRST SPECIES</span><h1>Tyrannosaurus rex</h1><p>Reveal a system. Select a structure. Follow the evidence.</p></div><button onClick={onSpecimen}>Compare with the fossil specimen <ArrowUpRight size={16}/></button></header>
 <LicensedSkeleton/><div className="anatomy-scope"><Layers size={20}/><p><strong>Schematic 3D teaching model.</strong> Shapes and positions are simplified. Soft tissues are inferred and some small structures are enlarged for selection. This is not a segmented fossil scan or a validated anatomical reconstruction.</p></div>
 <div className="anatomy-workspace">
 <aside className="anatomy-sidebar"><h2>Body systems</h2><div className="anatomy-system-list">{anatomySystems.map(s=><button key={s.id} aria-pressed={system===s.id} onClick={()=>changeSystem(s.id)} style={{borderLeftColor:s.colour}}><span>{s.name}</span><small>{anatomyParts.filter(p=>p.system===s.id).length} structures</small></button>)}</div><h2>Structures</h2><div className="anatomy-part-list">{anatomyParts.filter(p=>p.system===system).map((p,i)=><button key={p.id} aria-pressed={selected===p.id} onClick={()=>setSelected(p.id)}><span>{String(i+1).padStart(2,'0')}</span>{p.name}</button>)}</div></aside>
 <div className="anatomy-view"><div className="anatomy-view-title"><strong style={{color:activeSystem.colour}}>{activeSystem.name}</strong><span>Click a coloured structure to inspect it</span></div><AnatomyScene system={system} selected={selected} onSelect={setSelected} opacity={opacity} isolated={isolated} reset={reset} angle={angle}/><div className="anatomy-view-controls"><div role="group" aria-label="Camera angle">{(['side','front','top'] as const).map(a=><button key={a} aria-pressed={angle===a} onClick={()=>{setAngle(a);setReset(n=>n+1)}}>{a[0].toUpperCase()+a.slice(1)}</button>)}<button onClick={()=>{setAngle('side');setReset(n=>n+1)}} aria-label="Reset anatomy camera"><RotateCcw size={16}/></button></div><p>Drag to rotate · Pinch or scroll to zoom</p></div><div className="anatomy-layer-controls"><label htmlFor="anatomy-isolate">Isolate this system <Switch id="anatomy-isolate" checked={isolated} onCheckedChange={setIsolated}/></label><div><label htmlFor="anatomy-opacity">Body outline <span>{opacity}%</span></label><Slider id="anatomy-opacity" aria-label="Body outline opacity" value={[opacity]} onValueChange={v=>setOpacity(v[0])} min={0} max={30} step={1} disabled={isolated||system==='surface'}/></div></div><p className="anatomy-colour-note">Colours identify systems, not the animal’s original appearance. Bone context is faint when another system is selected.</p></div>
 <aside className="anatomy-detail" aria-live="polite" aria-atomic="true"><span className="anatomy-evidence">{part.kind}</span><h2>{part.name}</h2><h3>What it does</h3><p>{part.function}</p><h3>How we know</h3><p>{part.evidence}</p><div className="anatomy-limit"><h3>What remains uncertain</h3><p>{part.limit}</p></div><h3>Read the evidence</h3><a href={source.url} target="_blank" rel="noreferrer">{source.label} ↗</a><p className="anatomy-source-note">Evidence labels describe the basis of the explanation, not the accuracy of the displayed mesh.</p></aside>
 </div><p className="anatomy-credit">Educational model and website: <strong>Foo Huey Chyun</strong>. Scientific work remains credited to its authors. <a href="/credits">All credits and sources ↗</a></p>
 </section>
}
